package test;

import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;
import org.openqa.selenium.support.PageFactory;
import org.testng.Reporter;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import test.pages.LoginPage;
import test.pages.MainPage;
import test.util.DataProviders;
import test.util.LogLog4j;

/**
 * Created by Iakov Volf on 30.07.2015.
 */
public class CreateNewFolderTest extends TestsBaseClass {
    private static Logger Log = Logger.getLogger(LogLog4j.class.getName());


    public LoginPage loginPage;
    public MainPage mainPage;


    @BeforeClass
    public void setup() {
        PropertyConfigurator.configure("log4j.properties");
        loginPage = PageFactory.initElements(driver, LoginPage.class);
        mainPage = PageFactory.initElements(driver, MainPage.class);
    }

    @BeforeMethod
    public void beforeMethodSetUp() {
        try {
            loginPage.openLoginPage()
                    .waitUntilLoginPageIsLoaded()
                    .login("jakoff+11@gmail.com", "Piterpan1234.com");
            mainPage.waitUntilMainPageIsLoaded();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    //Positive test for creating new folder. Data (foldername) is generated by dataprovider
    @Test(groups = {"positive"},dataProviderClass = DataProviders.class, dataProvider = "folder")
    public void CreateFolder(String folderName) {

        try {
            mainPage.clickOnCreateFolderButton()
                    .enterFolderName(folderName)
                    .checkifNewFolderNameisCorrect(folderName);
            Reporter.log("Folder "+folderName+" is created");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

}
